version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=herbolario
    depends_on:
      - neo4j

  ui:
    build:
      context: ./ui
    volumes:
      - ./ui:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: "npm run dev"
    depends_on:
      - backend

  neo4j:
    image: neo4j:2025.06.2-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/herbolario
    volumes:
      - ./neo4j:/data
